const songData = {
  '101-suza': {
    title: '101 SUZA',
    video: '/videos/101suza.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=q7D8vUTAgl0&ab_channel=KDMExclusive',
      Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',
      Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona, Kaziragy',
      'Produced by Costa, Cope, GRBLD, Ilija',
      'Mix & Master: Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic Grooya',
      'Producer: Kaziragy',
      'Location PA: Aleksandar Pavlovic',
    ],
  },
  'pronto': {
    title: 'Pronto',
    video: '/videos/pronto.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=MJUEh39euKU&list=RDMJUEh39euKU&start_radio=1&ab_channel=KDMExclusive',
Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',     Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona',
      'Produced by Costa, Cope',
      'Mix & Master: Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic GrooYa',
      'Producer: Bozidar Draskovic',
      'Location PA: Aleksandar Pavlovic',
      'Gaffer: Lounis',
      'Editor: Ivan Leontic',
      'Colorist: Dr Cogu',
      'BTS: Mihajlo Ivanovic Ukun',
      'Casting director: Andjela Bucalovic',
      'Makeup: Katarina Suljagic',
      'Model: Nadja Milicevic',
    ],
  },
  'delinquente': {
    title: 'Delinquente',
    video: '/videos/delinquente.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=l6XwpRKUUfo&ab_channel=KDMExclusive',
Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',     Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona',
      'Produced by Costa',
      'Mix & Master: Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic Grooya',
      'Producer: Kaziragy',
      'Location PA: Aleksandar Pavlovic',
    ],
  },
  'mane': {
    title: 'Mane',
    video: '/videos/mane.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=dtlN2N1WM1M&ab_channel=KDMExclusive',
Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',     Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona',
      'Produced by One Music & Costa',
      'Mix & Master: Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic GrooYa',
      'Producer: Bozidar Draskovic',
      'Location PA: Aleksandar Pavlovic',
      'Gaffer: Lounis',
      'Editor: Dr Cogu',
      'Colorist: Dr Cogu',
      'BTS: Mihajlo Ivanovic Ukun',
      'Casting director: Andjela Bucalovic',
      'Makeup: Katarina Suljagic',
      'Model: Nadja Milicevic',
    ],
  },
  'knock-knock': {
    title: 'Knock Knock',
    video: '/videos/knock-knock.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=qF3mMaOnx6k&ab_channel=KDMExclusive',
Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',    Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona, Kaziragy',
      'Produced by Costa',
      'Mix & Master: Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic Grooya',
      'Producer: Kaziragy',
      'Location PA: Aleksandar Pavlovic',
    ],
  },
  'amorova-strela': {
    title: 'Amorova Strela',
    video: '/videos/amorova-strela.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=wsF-b-Z5dJU&ab_channel=KDMExclusive',
Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',  Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona',
      'Produced by One Music',
      'Mix & Master Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic GrooYa',
      'Producer: Bozidar Draskovic',
      'Location PA: Aleksandar Pavlovic',
      'Gaffer: Lounis',
      'Editor: Dr Cogu',
      'Colorist: Dr Cogu',
      'BTS: Mihajlo Ivanovic Ukun',
      'Casting director: Andjela Bucalovic',
      'Makeup: Katarina Suljagic',
      'Model: Nadja Milicevic',
    ],
  },
  'bonjour': {
    title: 'Bonjour',
    video: '/videos/bonjour.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=mY8D6l8pM0g&ab_channel=KDMExclusive',
Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',     Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona',
      'Produced by Costa',
      'Mix & Master: Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic Grooya',
      'Producer: Kaziragy',
      'Location PA: Aleksandar Pavlovic',
    ],
  },
   'original-badman': {
    title: 'Original Badman',
    video: '/videos/original-badman.mp4',
    links: {
      Youtube: 'https://www.youtube.com/watch?v=U_kWSnL7YYw&ab_channel=KDMExclusive',
Spotify: 'https://open.spotify.com/album/3LETlK3dYIX98jjZVyGXVW',   Deezer: 'https://www.deezer.com/en/album/780795941',
    },
    credits: [
      'Muzika: Corona',
      'Tekst: Corona',
      'Produced by: travebeats, One Music',
      'Mix & Master: Filip Mladenovic One Music',
      'Snimano u KDM Exclusive Studiju u Beogradu',
      '',
      'Director: Marko Mravik - Dr Cogu',
      'DP: Milos Grujic GrooYa',
      'Producer: Bozidar Draskovic',
      'Location PA: Aleksandar Pavlovic',
      'Gaffer: Lounis',
      '',
      'Editor: Ivan Leontic',
      'Colorist: Dr Cogu',
      'BTS: Mihajlo Ivanovic Ukun',
      '',
      'Casting director: Andjela Bucalovic',
      'Makeup: Katarina Suljagic',
      'Model: Nadja Milicevic',
    ],
  },
};

export default songData;
